# Generated by Django 6.0.3 on 2026-03-05 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_company_filial_accountant_filial_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(default='', max_length=250)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=30)),
                ('passport_serial', models.CharField(blank=True, max_length=9, null=True)),
                ('passport_pinfl', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('passport_got_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_got_region', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, max_length=100, null=True)),
                ('gov_address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.filial')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('contract_id', models.CharField(default='', max_length=50, unique=True)),
                ('payment', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('term', models.IntegerField(default=0)),
                ('product_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('fine', models.PositiveIntegerField(default=1)),
                ('monthly_income', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('monthly_spending', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('work_type', models.CharField(blank=True, max_length=50, null=True)),
                ('loans', models.IntegerField(default=0)),
                ('monthly_loan_payment', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('scoring', models.IntegerField(default=0)),
                ('payday', models.PositiveIntegerField(default=5)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('done', 'berildi'), ('approved', 'tasdiqlandi'), ('rejected', 'rad etildi'), ('pending', 'jarayonda'), ('paid', 'yopilgan')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='krd.client')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.filial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('paid_date', models.DateField(auto_now_add=True, null=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='krd.loan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_months', to='krd.loan')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbers', to='krd.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.filial')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krd.product'),
        ),
    ]
