# Generated by Django 5.2.5 on 2025-12-17 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0002_loan_loans_loan_monthly_loan_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.MinValueValidator(14)]),
        ),
    ]
