# Generated by Django 5.2.5 on 2025-12-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0003_alter_client_passport_pinfl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbers', to='krd.client'),
        ),
    ]
