# Generated by Django 5.2.5 on 2025-12-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0004_alter_phonenumber_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
