# Generated by Django 6.0.1 on 2026-01-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krd', '0006_remove_loan_paid_amount_paymentmonth_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='payday',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
